markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: William Sell
url: quannabe.github.io
description: A fantastic blog that is fantastic.
twitter: quannabe
github: quannabe
gravatar_url: http://www.gravatar.com/avatar/3ad71c7ec4c2332397aaf8b3241e744b.png